<?php

/**
 * @file
 * Functions to support theming in the Kisan Nidan theme.
 */

// /**
//  * Implements hook_preprocess_page().
//  */
// function kisan_nidan_preprocess_page(&$variables) {
//   // Add custom variables or modify page template variables here.
// }

// /**
//  * Implements hook_preprocess_node().
//  */
// function kisan_nidan_preprocess_node(&$variables) {
//   // Add custom variables or modify node template variables here.
// }

// /**
//  * Implements hook_preprocess_views_view().
//  */
// function kisan_nidan_preprocess_views_view(&$variables) {
//   // Add custom variables or modify views template variables here.
// }

// /**
//  * Implements hook_theme_suggestions_alter().
//  */
// function kisan_nidan_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
//   // Add custom theme suggestions here.
// }
